from __future__ import annotations

from typing import Protocol, runtime_checkable

from radar.contracts.report import RadarReportV2, StructuralIndicatorObservationV1
from radar.domain.models import Document, Event, EventDelta


@runtime_checkable
class DocumentRepository(Protocol):
    def save_documents(self, documents: list[Document]) -> None: ...

    def get_document(self, document_id: str) -> Document | None: ...

    def find_by_canonical_url(self, canonical_url: str) -> Document | None: ...

    def find_by_content_hash(self, content_hash: str) -> Document | None: ...

    def list_recent_documents(self, since: str) -> list[Document]: ...


@runtime_checkable
class EventRepository(Protocol):
    def save_event(self, event: Event) -> None: ...

    def get_event(self, event_id: str) -> Event | None: ...

    def find_recent_events(self, since: str) -> list[Event]: ...

    def attach_documents(self, event_id: str, document_ids: list[str]) -> None: ...

    def save_event_delta(self, event_id: str, delta: EventDelta, observed_at: str) -> None: ...

    def list_event_deltas(self, event_id: str) -> list[EventDelta]: ...

    def update_last_seen(self, event_id: str, last_seen_at: str) -> None: ...

    def list_active_events(self) -> list[Event]: ...


@runtime_checkable
class ReportRepository(Protocol):
    def save_report(self, report: RadarReportV2) -> None: ...

    def get_report(self, report_id: str) -> RadarReportV2 | None: ...

    def get_report_by_date(self, report_date: str, profile: str) -> RadarReportV2 | None: ...

    def get_latest_report(self, profile: str | None = None) -> RadarReportV2 | None: ...

    def list_reports(self, profile: str | None = None) -> list[RadarReportV2]: ...


@runtime_checkable
class IndicatorRepository(Protocol):
    def save_indicator_observation(self, observation: StructuralIndicatorObservationV1) -> None: ...

    def list_indicator_observations(self, indicator_id: str) -> list[StructuralIndicatorObservationV1]: ...

    def get_rolling_window(self, indicator_id: str, days: int) -> list[StructuralIndicatorObservationV1]: ...
